// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://megrjwucmhnhziylpgpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZ3Jqd3VjbWhuaHppeWxwZ3B1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDE0MzEsImV4cCI6MjA2NTgxNzQzMX0.D8arv7mai3DhQDjNqjWcK5tBhJnmqVrFxXWO4vHkRRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);